version: '3.9'
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_SERVICE_SERVICE_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=students
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - students
    depends_on: 
      - db
    
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=students
    networks: 
      - students
    volumes:
      - /d/mysql/data:/var/lib/mysql       
      
networks:
  students:
